Repository CARTAvis/carta-frontend, pull requests merged in 2024-06, with the labels that each got.

#2380 Yuhsuan/fix catalog import
  CHANGELOG.md
  src/stores/AppStore/AppStore.ts
Labels: awaiting code review

#2351 Thchang/582 improve coordinate system selection when loading images
  CHANGELOG.md
  src/stores/AppStore/AppStore.ts
  src/stores/Frame/FrameStore.ts
  src/stores/OverlayStore/OverlayStore.ts
Labels: awaiting merge

#2385 supporting polyline as a pv cut
  CHANGELOG.md
  src/components/PvGenerator/PvGeneratorComponent.tsx
  src/stores/Frame/FrameStore.ts
  src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts
Labels: requiring backend, awaiting merge

#2360 Yuhsuan/1204 color blending
  CHANGELOG.md
  docs_website/docs/code-snippet-tutorial/image-blending.mdx
  docs_website/docs/code-snippet-tutorial/quick-start.mdx
  src/HotkeyWrapper.tsx
  src/components/Animator/AnimatorComponent.tsx
  src/components/CursorInfo/CursorInfoComponent.tsx
  src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
  src/components/ImageView/ContourView/ContourViewComponent.tsx
  src/components/ImageView/ImagePanel/ImagePanelComponent.tsx
  src/components/ImageView/ImageViewComponent.tsx
  src/components/ImageView/ImageViewSettingsPanel/ImageViewSettingsPanelComponent.tsx
  src/components/ImageView/Overlay/OverlayComponent.tsx
  src/components/ImageView/RasterView/RasterViewComponent.tsx
  src/components/ImageView/VectorOverlayView/VectorOverlayView.tsx
  src/components/LayerList/LayerListComponent.tsx
  src/components/Menu/RootMenuComponent.tsx
  src/components/PvGenerator/PvPreviewComponent.tsx
  src/components/RenderConfig/ColorBlendingConfigComponent/ColorBlendingConfigComponent.scss
  src/components/RenderConfig/ColorBlendingConfigComponent/ColorBlendingConfigComponent.tsx
  src/components/RenderConfig/RenderConfigComponent.tsx
  src/components/SpectralProfiler/ProfileFittingComponent/ProfileFittingComponent.tsx
  src/models/ImageType/ImageType.ts
  src/models/index.ts
  src/stores/AnimatorStore/AnimatorStore.ts
  src/stores/AppStore/AppStore.ts
  src/stores/Catalog/CatalogStore.ts
  src/stores/ColorBlendingStore/ColorBlendingStore.test.ts
  src/stores/ColorBlendingStore/ColorBlendingStore.ts
  src/stores/Frame/FrameStore.ts
  src/stores/ImageViewConfig/ImageViewConfigStore.test.ts
  src/stores/ImageViewConfig/ImageViewConfigStore.ts
  src/stores/OverlayStore/OverlayStore.ts
  src/stores/Widgets/LayerListWidgetStore/LayerListWidgetStore.ts
  src/stores/Widgets/WidgetsStore.ts
  src/stores/index.ts
Labels: awaiting merge

#2373 Yuhsuan/stores null check
  src/components/Shared/LinePlot/LinePlotComponent.tsx
  src/components/Shared/Tables/FilterableTableComponent.tsx
  src/models/AbstractCatalogProfile/AbstractCatalogProfile.ts
  src/models/Layout/LayoutConfig.ts
  src/models/Spectral/SpectralDefinition.ts
  src/services/BackendService.ts
  src/stores/AlertStore/AlertStore.ts
  src/stores/AppStore/AppStore.ts
  src/stores/Catalog/CatalogProfileStore.ts
  src/stores/Catalog/CatalogStore.ts
  src/stores/CatalogOnlineQuery/CatalogOnlineQueryConfigStore.ts
  src/stores/CatalogOnlineQuery/CatalogOnlineQueryProfileStore.ts
  src/stores/FileBrowserStore/FileBrowserStore.ts
  src/stores/Frame/FrameStore.ts
  src/stores/ImageFittingStore/ImageFittingStore.ts
  src/stores/LayoutStore/LayoutStore.ts
  src/stores/ProfileFittingStore/ProfileFittingStore.ts
  src/stores/ProfileSmoothingStore/ProfileSmoothingStore.ts
  src/stores/Snippet/SnippetStore.ts
  src/stores/SpatialProfileStore/SpatialProfileStore.ts
  src/stores/SpectralProfileStore/SpectralProfileStore.ts
  src/stores/Widgets/CatalogWidget/CatalogPlotWidgetStore.ts
  src/stores/Widgets/CatalogWidget/CatalogWidgetStore.ts
  src/stores/Widgets/HistogramWidgetStore/HistogramWidgetStore.ts
  src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts
  src/stores/Widgets/RegionWidgetStore/RegionWidgetStore.ts
  src/stores/Widgets/RenderConfigWidgetStore/RenderConfigWidgetStore.ts
  src/stores/Widgets/SpatialProfileWidgetStore/SpatialProfileWidgetStore.ts
  src/stores/Widgets/SpectralLineQueryWidgetStore/SpectralLineQueryWidgetStore.ts
  src/stores/Widgets/SpectralProfileWidget/SpectralProfileSelectionStore.ts
  src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
  src/stores/Widgets/StatsWidgetStore/StatsWidgetStore.ts
  src/stores/Widgets/StokesAnalysisWidgetStore/StokesAnalysisWidgetStore.ts
  src/stores/Widgets/WidgetsStore.ts
  src/utilities/Processed/Processed.ts
  src/utilities/color/color.ts
  src/utilities/fitting_heuristics/fitting_heuristics.ts
  src/utilities/sorting/sorting.ts
  src/utilities/table/table.ts
  tsc-silent.config.js
Labels: awaiting merge
