Repository CARTAvis/carta-frontend, pull requests merged in 2024-01, with the labels that each got.

#2327 fix pv preview
  src/components/ImageView/ContourView/ContourViewComponent.tsx
Labels: awaiting merge

#2322 Yuhsuan/2293 vector on matched frame
  CHANGELOG.md
  src/components/ImageView/VectorOverlayView/VectorOverlayView.tsx
Labels: backport, awaiting merge

#2323 Yuhsuan/2314 telemetry dialog display
  CHANGELOG.md
  src/components/Dialogs/TelemetryDialog/TelemetryDialogComponent.tsx
  src/components/Menu/RootMenuComponent.tsx
  src/stores/PreferenceStore/PreferenceStore.ts
Labels: backport, awaiting merge

#2259 Thchang/improve handling non-standard spectral axis images
  CHANGELOG.md
  src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx
  src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx
  src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx
  src/models/Spectral/SpectralDefinition.ts
  src/stores/FileBrowserStore/FileBrowserStore.ts
  src/stores/Frame/FrameStore.ts
Labels: awaiting merge

#2320 carli/2318_missing_region_telemetry
  src/services/TelemetryService.ts
  src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts
  src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
Labels: backport, awaiting merge

#2324 Yuhsuan/2252 fix spatial match
  CHANGELOG.md
  src/stores/Frame/FrameStore.ts
  src/stores/OverlayStore/OverlayStore.ts
Labels: backport, awaiting merge

#2317 carli/2304_slow_telemetry_start
  CHANGELOG.md
  src/services/TelemetryService.ts
  src/stores/AppStore/AppStore.ts
Labels: backport

#2334 Yuhsuan/4.1.0 version update
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/CatalogOverlay/CatalogPlotComponent/CatalogPlotComponent.tsx
  src/components/Dialogs/AboutDialog/AboutDialogComponent.tsx
  src/components/Dialogs/ContourDialog/ContourDialogComponent.tsx
  src/components/Dialogs/TelemetryDialog/TelemetryDialogComponent.tsx
  src/components/ImageView/VectorOverlayView/VectorOverlayView.tsx
  src/components/Menu/RootMenuComponent.tsx
  src/components/PvGenerator/PvGeneratorComponent.tsx
  src/components/SpatialProfiler/SpatialProfilerSettingsPanelComponent/SpatialProfilerSettingsPanelComponent.tsx
  src/services/TelemetryService.ts
  src/services/TileService.ts
  src/stores/AppStore/AppStore.ts
  src/stores/FileBrowserStore/FileBrowserStore.ts
  src/stores/Frame/FrameStore.ts
  src/stores/OverlayStore/OverlayStore.ts
  src/stores/PreferenceStore/PreferenceStore.ts
  src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts
  src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
  src/stores/Widgets/WidgetsStore.ts
  src/utilities/CatalogApiProcessed/CatalogApiProcessed.ts
Labels: awaiting testing
