Repository CARTAvis/carta-frontend, pull requests merged in 2025-06, with the labels that each got.

#2519 Yuhsuan/2492 channel map overlay
  src/components/CursorInfo/CursorInfoComponent.tsx
  src/components/Dialogs/OnlineDataQueryDialog/CatalogOnlineQueryComponent.tsx
  src/components/Dialogs/RegionDialog/CompassRulerRegionForm/CompassRulerRegionForm.tsx
  src/components/Dialogs/RegionDialog/EllipticalRegionForm/EllipticalRegionForm.tsx
  src/components/Dialogs/RegionDialog/LineRegionForm/LineRegionForm.tsx
  src/components/Dialogs/RegionDialog/PointRegionForm/PointRegionForm.tsx
  src/components/Dialogs/RegionDialog/PolygonRegionForm/PolygonRegionForm.tsx
  src/components/Dialogs/RegionDialog/RectangularRegionForm/RectangularRegionForm.tsx
  src/components/Dialogs/WorkspaceDialog/WorkspaceDialogComponent.tsx
  src/components/ImageView/CatalogView/CatalogViewGLComponent.tsx
  src/components/ImageView/ChannelMapView/ChannelMapLabelComponent.tsx
  src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
  src/components/ImageView/Colorbar/ColorbarComponent.tsx
  src/components/ImageView/ContourView/ContourViewComponent.tsx
  src/components/ImageView/ImagePanel/ImagePanelComponent.tsx
  src/components/ImageView/ImageViewComponent.tsx
  src/components/ImageView/ImageViewSettingsPanel/ImageViewSettingsPanelComponent.tsx
  src/components/ImageView/Overlay/OverlayComponent.tsx
  src/components/ImageView/RasterView/RasterViewComponent.tsx
  src/components/ImageView/RegionView/CompassAndRulerAnnotationComponent.tsx
  src/components/ImageView/RegionView/RegionViewComponent.tsx
  src/components/ImageView/Toolbar/ToolbarComponent.tsx
  src/components/ImageView/VectorOverlayView/VectorOverlayView.tsx
  src/components/PvGenerator/PvPreviewComponent.tsx
  src/components/RegionList/RegionListComponent.tsx
  src/components/Shared/CoordNumericInput/CoordNumericInput.tsx
  src/components/Shared/CoordinateComponent/CoordinateComponent.tsx
  src/components/SpatialProfiler/SpatialProfilerComponent.tsx
  src/stores/AppStore/AppStore.ts
  src/stores/Catalog/CatalogStore.ts
  src/stores/CatalogOnlineQuery/CatalogOnlineQueryConfigStore.ts
  src/stores/Frame/ColorbarStore/ColorbarStore.ts
  src/stores/Frame/FrameStore.ts
  src/stores/ImageFittingStore/ImageFittingStore.ts
  src/stores/OverlayStore/OverlayStore.ts
  src/stores/PreferenceStore/PreferenceStore.ts
  src/stores/Widgets/PvGeneratorWidgetStore/PvGeneratorWidgetStore.ts
  src/utilities/wcs/wcs.ts
Labels: awaiting merge

#2537 Don't require non-empty directory to export region file
  src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx
Labels: awaiting code review, awaiting testing

#2522 Yuhsuan/flux density unit
  CHANGELOG.md
  src/components/Stats/StatsComponent.tsx
  src/utilities/units/units.test.ts
  src/utilities/units/units.ts
Labels: requiring backend, awaiting merge

#2540 upgrade zfp to 1.0.1
  wasm_libs/build_zfp.sh
  wasm_libs/zfp.md5
Labels: blocked, requiring backend, awaiting merge

#2547 Yuhsuan/2498 external service acknowledgement
  src/components/Dialogs/AboutDialog/AboutDialogComponent.scss
  src/components/Dialogs/AboutDialog/AboutDialogComponent.tsx
Labels: awaiting merge

#2552 Yuhsuan/2550 pv image axis conversion
  CHANGELOG.md
  src/components/Dialogs/FileBrowser/ImageSave/ImageSaveComponent.tsx
  src/components/ImageView/ImageViewSettingsPanel/ImageViewSettingsPanelComponent.tsx
  src/components/PvGenerator/PvGeneratorComponent.tsx
  src/components/Shared/SpectralSettings/SpectralSettingsComponent.tsx
  src/components/SpectralProfiler/MomentGeneratorComponent/MomentGeneratorComponent.tsx
  src/components/SpectralProfiler/SpectralProfilerSettingsPanelComponent/SpectralProfilerSettingsPanelComponent.tsx
  src/components/StokesAnalysis/StokesAnalysisSettingsPanelComponent/StokesAnalysisSettingsPanelComponent.tsx
Labels: awaiting merge

#2542 Yuhsuan/2492 channel map control widget
  CHANGELOG.md
  src/components/ChannelMapControl/ChannelMapControlComponent.scss
  src/components/ChannelMapControl/ChannelMapControlComponent.tsx
  src/components/ImageView/ChannelMapView/ChannelMapLabelComponent.tsx
  src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
  src/components/ImageView/Colorbar/ColorbarComponent.tsx
  src/components/ImageView/ImageViewComponent.tsx
  src/components/ImageView/ImageViewSettingsPanel/ImageViewSettingsPanelComponent.tsx
  src/components/Shared/AutoColorPicker/AutoColorPickerComponent.tsx
  src/components/Shared/FontSelect/FontSelect.tsx
  src/components/Shared/index.ts
  src/stores/ChannelMapStore/ChannelMapStore.ts
Labels: awaiting merge

#2545 ksw/update online help urls
  src/components/ChannelMapControl/ChannelMapControlComponent.tsx
  src/components/FloatingWidget/FloatingWidgetComponent.tsx
  src/components/HelpDrawer/HelpDrawerComponent.tsx
  src/components/RenderConfig/RenderConfigComponent.tsx
  src/stores/HelpStore/HelpStore.ts
  src/stores/Widgets/WidgetsStore.ts
Labels: awaiting merge
